sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid:  (library jar  /home/user/scala/trunk/lib/scala-library.jar)
	at sbt.ScalaInstance$.slowActualVersion(ScalaInstance.scala:130)
	at sbt.ScalaInstance$.sbt$ScalaInstance$$actualVersion(ScalaInstance.scala:127)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:82)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:69)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:404)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:403)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.Properties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.ScalaInstance$.slowActualVersion(ScalaInstance.scala:130)
	at sbt.ScalaInstance$.sbt$ScalaInstance$$actualVersion(ScalaInstance.scala:127)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:82)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:69)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:404)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:403)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(*:[31mscalaInstance[0m) sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid:  (library jar  /home/user/scala/trunk/lib/scala-library.jar)[0m
